import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';

export function registerHttpdHandlerScaffoldTool(server: McpServer): void {
  server.registerTool(
    'jerboa_httpd_handler_scaffold',
    {
      title: 'HTTP Handler Scaffold',
      description:
        'Generate an HTTP server handler skeleton using (std net http) from route specifications. ' +
        'Produces a complete server setup with routing, JSON request/response helpers, ' +
        'error handling, and graceful shutdown.',
      annotations: {
        readOnlyHint: true,
        idempotentHint: true,
      },
      inputSchema: {
        routes: z
          .array(
            z.object({
              method: z.string().describe('HTTP method (GET, POST, PUT, DELETE)'),
              path: z.string().describe('URL path pattern (e.g. /users, /users/:id)'),
              handler: z.string().describe('Handler function name'),
            }),
          )
          .describe('Route specifications'),
        port: z
          .number()
          .optional()
          .describe('Server port (default: 8080)'),
        module_name: z
          .string()
          .optional()
          .describe('Module name for the generated code'),
      },
    },
    async ({ routes, port, module_name }) => {
      const serverPort = port || 8080;
      const modName = module_name || 'my-server';

      const sections: string[] = [];

      // Generate imports
      sections.push(`;;; ${modName} — HTTP server generated by jerboa_httpd_handler_scaffold`);
      sections.push('(import (jerboa prelude))');
      sections.push('(import (std net http))');
      sections.push('(import (std text json))');
      sections.push('');
      sections.push('(export main)');
      sections.push('');

      // JSON helpers
      sections.push(';;; JSON response helper');
      sections.push('(define (json-response status data)');
      sections.push('  (list status');
      sections.push('    \'(("Content-Type" . "application/json"))');
      sections.push('    (json->string data)))');
      sections.push('');
      sections.push('(define (json-error message (status 400))');
      sections.push('  (json-response status `((error . ,message))))');
      sections.push('');

      // Request body parser
      sections.push(';;; Parse JSON request body');
      sections.push('(define (parse-json-body req)');
      sections.push('  (let ((body (http-request-body req)))');
      sections.push('    (if body');
      sections.push('      (guard (e [else #f])');
      sections.push('        (json->datum (utf8->string body)))');
      sections.push('      #f)))');
      sections.push('');

      // Path parameter extraction
      sections.push(';;; Extract path parameter');
      sections.push('(define (path-param path pattern)');
      sections.push('  ;; Simple path matching — extract segment after prefix');
      sections.push('  (and (string-prefix? pattern path)');
      sections.push('       (substring path (string-length pattern) (string-length path))))');
      sections.push('');

      // Generate handler functions
      for (const route of routes) {
        sections.push(`;;; ${route.method} ${route.path}`);
        sections.push(`(define (${route.handler} req)`);

        if (route.method === 'GET' && route.path.includes(':')) {
          // Handler with path params
          const prefix = route.path.replace(/:[^/]+$/, '');
          sections.push(`  (let ((id (path-param (http-request-path req) "${prefix}")))`);
          sections.push(`    (if id`);
          sections.push(`      (json-response 200 \`((id . ,id) (status . "ok")))`);
          sections.push(`      (json-error "Not found" 404))))`);
        } else if (route.method === 'POST' || route.method === 'PUT') {
          sections.push('  (let ((body (parse-json-body req)))');
          sections.push('    (if body');
          sections.push('      (begin');
          sections.push(`        ;; TODO: Process ${route.method} request body`);
          sections.push('        (json-response 201 \'((status . "created"))))');
          sections.push('      (json-error "Invalid JSON body"))))');
        } else if (route.method === 'DELETE') {
          const prefix = route.path.replace(/:[^/]+$/, '');
          sections.push(`  (let ((id (path-param (http-request-path req) "${prefix}")))`);
          sections.push('    (if id');
          sections.push('      (begin');
          sections.push('        ;; TODO: Delete resource');
          sections.push('        (json-response 200 \'((status . "deleted"))))');
          sections.push('      (json-error "Not found" 404))))');
        } else {
          sections.push(`  ;; TODO: Implement ${route.method} ${route.path}`);
          sections.push('  (json-response 200 \'((status . "ok"))))');
        }
        sections.push('');
      }

      // Router
      sections.push(';;; Router');
      sections.push('(define (router req)');
      sections.push('  (let ((method (http-request-method req))');
      sections.push('        (path (http-request-path req)))');
      sections.push('    (cond');
      for (const route of routes) {
        if (route.path.includes(':')) {
          const prefix = route.path.replace(/:[^/]+$/, '');
          sections.push(
            `      ((and (equal? method "${route.method}") (string-prefix? "${prefix}" path))`,
          );
        } else {
          sections.push(
            `      ((and (equal? method "${route.method}") (equal? path "${route.path}"))`,
          );
        }
        sections.push(`       (${route.handler} req))`);
      }
      sections.push('      (else');
      sections.push('       (json-error "Not found" 404)))))');
      sections.push('');

      // Main entry point
      sections.push(';;; Main entry point');
      sections.push('(define (main . args)');
      sections.push(`  (let ((port ${serverPort}))`);
      sections.push('    (display (string-append "Starting server on port " (number->string port) "\\n"))');
      sections.push('    (http-serve port router)))');
      sections.push('');
      sections.push('(apply main (cdr (command-line)))');

      const code = sections.join('\n');

      const output = [
        `## HTTP Server Scaffold: ${modName}`,
        '',
        `Routes: ${routes.length}`,
        `Port: ${serverPort}`,
        '',
        '```scheme',
        code,
        '```',
        '',
        '### Usage',
        '1. Save to `lib/main.ss`',
        '2. Run with `scheme --libdirs lib --script lib/main.ss`',
        '',
        '**Note**: Verify http imports with `jerboa_module_exports (std net http)` — ',
        'the API may vary between Jerboa versions.',
      ];

      return {
        content: [{ type: 'text' as const, text: output.join('\n') }],
      };
    },
  );
}
