import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import { runChez, buildPreamble, RESULT_MARKER, ERROR_MARKER } from '../chez.js';

interface RenameMapping {
  unsafeName: string;
  safeName: string;
  sourceModule: string;
}

export function registerSafePreludeGeneratorTool(server: McpServer): void {
  server.registerTool(
    'jerboa_safe_prelude_generate',
    {
      title: 'Safe Prelude Generator',
      description:
        'Generates a safe-by-default prelude module that re-exports safe wrapper functions ' +
        'under the original (unsafe) names. Given a safe wrapper module (e.g., (std safe)) and ' +
        'the original module (e.g., (std db sqlite)), generates a library that imports the safe ' +
        'versions and re-exports them with stripped "safe-" prefixes. Also excludes specified ' +
        'dangerous exports (foreign-procedure, c-lambda, etc.).',
      annotations: { readOnlyHint: true, idempotentHint: true },
      inputSchema: {
        safe_module: z.string().describe('Module providing safe wrappers (e.g. "(std safe)" or "std/safe")'),
        safe_prefix: z.string().optional().describe('Prefix to strip from safe names (default: "safe-")'),
        unsafe_modules: z.array(z.string()).optional().describe('Original unsafe modules to shadow (auto-detected from safe module if omitted)'),
        exclude_exports: z.array(z.string()).optional().describe('Dangerous exports to exclude (e.g. ["foreign-procedure", "c-lambda"])'),
        library_name: z.string().optional().describe('Name for the generated library (default: "(jerboa prelude safe)")'),
        jerboa_home: z.string().optional().describe('Path to Jerboa home directory'),
      },
    },
    async ({ safe_module, safe_prefix, unsafe_modules, exclude_exports, library_name, jerboa_home }) => {
      const prefix = safe_prefix ?? 'safe-';
      const libName = library_name ?? '(jerboa prelude safe)';
      const excludeSet = new Set(exclude_exports ?? ['foreign-procedure', 'c-lambda', 'load-shared-object', 'eval', 'environment']);

      // Normalize module path
      const normalizeModule = (m: string): string => {
        if (m.startsWith('(')) return m;
        const stripped = m.startsWith(':') ? m.slice(1) : m;
        return `(${stripped.replace(/\//g, ' ')})`;
      };

      const safeModNorm = normalizeModule(safe_module);

      // Step 1: Introspect the safe module to find safe- prefixed exports
      const script = `
${buildPreamble([safe_module])}

(let ([exports (library-exports '${safeModNorm})])
  (for-each
    (lambda (sym)
      (display (symbol->string sym))
      (newline))
    exports))
`;

      const result = await runChez(script, { jerboaHome: jerboa_home, timeout: 15_000 });

      if (result.exitCode !== 0) {
        const errMsg = result.stderr || result.stdout || 'Unknown error';
        return {
          content: [{
            type: 'text' as const,
            text: `Failed to introspect ${safeModNorm}:\n${errMsg.trim()}`,
          }],
          isError: true,
        };
      }

      const allExports = result.stdout.trim().split('\n').filter(Boolean);
      const safeExports = allExports.filter(name => name.startsWith(prefix));
      const otherExports = allExports.filter(name => !name.startsWith(prefix) && !excludeSet.has(name));

      // Build rename mappings
      const mappings: RenameMapping[] = [];
      for (const safeName of safeExports) {
        const unsafeName = safeName.slice(prefix.length);
        if (excludeSet.has(unsafeName)) continue;
        mappings.push({
          unsafeName,
          safeName,
          sourceModule: safe_module,
        });
      }

      // Step 2: Generate the library
      const lines: string[] = [];
      lines.push(`;;; ${libName} — Auto-generated safe-by-default prelude`);
      lines.push(`;;; Generated by jerboa_safe_prelude_generate`);
      lines.push(`;;; Safe wrappers from ${safeModNorm} re-exported under original names`);
      lines.push('');
      lines.push(`(library ${libName}`);
      lines.push('  (export');

      // Export renamed safe functions under original names
      for (const m of mappings) {
        lines.push(`    ${m.unsafeName}    ;; → ${m.safeName}`);
      }
      // Export other non-excluded symbols as-is
      for (const name of otherExports) {
        lines.push(`    ${name}`);
      }
      lines.push('  )');
      lines.push('');
      lines.push(`  (import (jerboa prelude))`);
      lines.push(`  (import ${safeModNorm})`);

      // Add import exclusions for unsafe modules to avoid conflicts
      if (unsafe_modules && unsafe_modules.length > 0) {
        for (const um of unsafe_modules) {
          const umNorm = normalizeModule(um);
          const conflictingNames = mappings.map(m => m.unsafeName);
          if (conflictingNames.length > 0) {
            lines.push(`  ;; Shadow unsafe versions from ${umNorm}`);
          }
        }
      }

      lines.push('');
      lines.push('  ;; Re-export safe versions under original names');
      for (const m of mappings) {
        lines.push(`  (define ${m.unsafeName} ${m.safeName})`);
      }

      lines.push(')');
      lines.push('');

      const generatedCode = lines.join('\n');

      // Build report
      const sections: string[] = [];
      sections.push('Safe Prelude Generator');
      sections.push(`Source module: ${safeModNorm}`);
      sections.push(`Total exports: ${allExports.length}`);
      sections.push(`Safe wrappers found: ${safeExports.length} (prefix: "${prefix}")`);
      sections.push(`Rename mappings: ${mappings.length}`);
      sections.push(`Excluded: ${excludeSet.size} dangerous symbols`);
      sections.push(`Pass-through: ${otherExports.length} symbols`);
      sections.push('');

      if (mappings.length > 0) {
        sections.push('Mappings:');
        for (const m of mappings) {
          sections.push(`  ${m.unsafeName} → ${m.safeName}`);
        }
        sections.push('');
      }

      sections.push('--- Generated Library ---');
      sections.push('');
      sections.push(generatedCode);

      return {
        content: [{ type: 'text' as const, text: sections.join('\n') }],
      };
    },
  );
}
